name: monorepo_styling
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5

  cool_package: 1.0.0
  domain_package: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.2

flutter:
  uses-material-design: true